/**
 * -----------------------------------------------------------------------------------
 * [실습 1] Supabase CRUD & Auth 통합 연동 실습
 * -----------------------------------------------------------------------------------
 * [데이터베이스 테이블 생성 SQL]
 * 
 * -- 1. 게시글 테이블 생성
 * create table posts (
 *   id bigint generated by default as identity primary key,
 *   title text not null,
 *   content text not null,
 *   created_at timestamp with time zone default now() not null
 * );
 * 
 * -- 2. 댓글 테이블 생성 (posts 테이블의 id를 참조하며, 게시글 삭제 시 관련 댓글도 자동 삭제)
 * create table comments (
 *   id bigint generated by default as identity primary key,
 *   post_id bigint references posts(id) on delete cascade not null,
 *   commenter text not null,
 *   content text not null,
 *   created_at timestamp with time zone default now() not null
 * );
 * -----------------------------------------------------------------------------------
 */

// 1. Supabase 접속 설정값 (사용자 정보로 대체 필요)
const SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL"; 
const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"; 

let supabase = null;

// 애플리케이션 초기화
document.addEventListener("DOMContentLoaded", () => {
  initSupabase();
  checkSession();
  fetchPosts();
  bindEvents();
});

// Supabase 클라이언트 객체 생성
function initSupabase() {
  if (SUPABASE_URL === "YOUR_SUPABASE_PROJECT_URL" || SUPABASE_ANON_KEY === "YOUR_SUPABASE_ANON_KEY") {
    console.warn("Supabase 접속을 위해 script.js 상단의 URL과 Key 값을 변경해 주세요.");
    return;
  }
  supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
}

// 이벤트 핸들러 바인딩
function bindEvents() {
  const postForm = document.getElementById("post-form");
  if (postForm) {
    postForm.addEventListener("submit", handlePostSubmit);
  }

  const refreshBtn = document.getElementById("btn-refresh");
  if (refreshBtn) {
    refreshBtn.addEventListener("click", fetchPosts);
  }

  // 회원가입 및 로그인 핸들러 등록
  document.getElementById("btn-signup")?.addEventListener("click", handleSignUp);
  document.getElementById("btn-signin")?.addEventListener("click", handleSignIn);
  document.getElementById("btn-signout")?.addEventListener("click", handleSignOut);
}

// ==========================================
// 인증(Auth) 로직
// ==========================================

// 현재 로그인 상태 점검 및 UI 반영
async function checkSession() {
  if (!supabase) return;

  const { data: { session }, error } = await supabase.auth.getSession();
  if (error) {
    console.error("세션 체크 실패:", error.message);
    return;
  }
  updateAuthUI(session);
}

// 회원가입
// [참고] 이메일 외에 구글, 깃허브 등 소셜 로그인(OAuth)을 연동하여 인증하고 싶다면 다음과 같은 형식으로 호출하여 확장할 수도 있습니다.
// await supabase.auth.signInWithOAuth({ provider: 'github' });
async function handleSignUp() {
  if (!supabase) return alert("Supabase 설정을 완료해 주세요.");

  const email = document.getElementById("auth-email").value.trim();
  const password = document.getElementById("auth-password").value.trim();

  if (!email || !password) {
    return alert("이메일과 비밀번호를 입력해 주세요.");
  }

  const { data, error } = await supabase.auth.signUp({ email, password });

  if (error) {
    alert("회원가입 실패: " + error.message);
  } else {
    alert("회원가입 완료. 로그인 혹은 이메일 인증 절차를 완료해 주세요.");
  }
}

// 이메일 로그인
async function handleSignIn() {
  if (!supabase) return alert("Supabase 설정을 완료해 주세요.");

  const email = document.getElementById("auth-email").value.trim();
  const password = document.getElementById("auth-password").value.trim();

  if (!email || !password) {
    return alert("이메일과 비밀번호를 입력해 주세요.");
  }

  const { data, error } = await supabase.auth.signInWithPassword({ email, password });

  if (error) {
    alert("로그인 실패: " + error.message);
  } else {
    updateAuthUI(data.session);
  }
}

// 로그아웃
async function handleSignOut() {
  if (!supabase) return;

  const { error } = await supabase.auth.signOut();
  if (error) {
    alert("로그아웃 실패: " + error.message);
  } else {
    updateAuthUI(null);
  }
}

// 인증 상태에 따른 UI 요소 제어
function updateAuthUI(session) {
  const loggedOutBox = document.getElementById("auth-logged-out");
  const loggedInBox = document.getElementById("auth-logged-in");
  const userEmailDisplay = document.getElementById("user-email-display");

  if (session && session.user) {
    loggedOutBox.classList.add("hidden");
    loggedInBox.classList.remove("hidden");
    userEmailDisplay.textContent = session.user.email;
  } else {
    loggedOutBox.classList.remove("hidden");
    loggedInBox.classList.add("hidden");
    userEmailDisplay.textContent = "";
  }
}

// ==========================================
// 게시글 CRUD 로직
// ==========================================

// [Create] 게시글 생성
async function handlePostSubmit(e) {
  e.preventDefault();
  if (!supabase) return alert("Supabase 설정을 완료해 주세요.");

  const titleInput = document.getElementById("post-title");
  const contentInput = document.getElementById("post-content");

  const title = titleInput.value.trim();
  const content = contentInput.value.trim();

  try {
    const { error } = await supabase
      .from("posts")
      .insert([{ title, content }]);

    if (error) throw error;

    titleInput.value = "";
    contentInput.value = "";
    fetchPosts();
  } catch (error) {
    alert("등록 에러: " + error.message);
  }
}

// [Read] 게시글 목록 조회 (Supabase REST API 작동 원리 실습을 위해 이 함수만 Axios를 사용합니다)
async function fetchPosts() {
  const container = document.getElementById("posts-container");
  if (SUPABASE_URL === "YOUR_SUPABASE_PROJECT_URL" || SUPABASE_ANON_KEY === "YOUR_SUPABASE_ANON_KEY") {
    container.innerHTML = `<div class="status-msg">접속 정보가 설정되지 않았습니다.</div>`;
    return;
  }

  container.innerHTML = `<div class="status-msg">데이터 로딩 중...</div>`;

  try {
    // Supabase가 테이블 생성 시 자동 빌드한 REST API로 직접 GET 요청 전송
    const response = await axios.get(`${SUPABASE_URL}/rest/v1/posts`, {
      headers: {
        'apikey': SUPABASE_ANON_KEY,
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
      },
      params: {
        select: '*',
        order: 'created_at.desc' // 내림차순 정렬 파라미터 지정
      }
    });

    const posts = response.data;

    if (!posts || posts.length === 0) {
      container.innerHTML = `<div class="status-msg">등록된 게시글이 없습니다.</div>`;
      return;
    }

    container.innerHTML = "";
    for (const post of posts) {
      const card = await createPostCardElement(post);
      container.appendChild(card);
    }
  } catch (error) {
    container.innerHTML = `<div class="status-msg">에러 발생: ${error.message}</div>`;
  }
}

// [Update] 게시글 수정
async function updatePost(postId, currentTitle, currentContent) {
  if (!supabase) return;

  const newTitle = prompt("수정할 제목을 입력하세요:", currentTitle);
  if (newTitle === null) return;

  const newContent = prompt("수정할 내용을 입력하세요:", currentContent);
  if (newContent === null) return;

  if (!newTitle.trim() || !newContent.trim()) {
    return alert("제목과 내용은 공백일 수 없습니다.");
  }

  try {
    const { error } = await supabase
      .from("posts")
      .update({ title: newTitle.trim(), content: newContent.trim() })
      .eq("id", postId);

    if (error) throw error;

    fetchPosts();
  } catch (error) {
    alert("수정 실패: " + error.message);
  }
}

// [Delete] 게시글 삭제
async function deletePost(postId) {
  if (!supabase) return;
  if (!confirm("게시글을 삭제하시겠습니까? (관련 댓글도 함께 삭제됩니다)")) return;

  try {
    const { error } = await supabase
      .from("posts")
      .delete()
      .eq("id", postId);

    if (error) throw error;

    fetchPosts();
  } catch (error) {
    alert("삭제 실패: " + error.message);
  }
}

// ==========================================
// 댓글 연동 로직
// ==========================================

// 특정 게시글의 댓글 조회
async function loadComments(postId, listContainer) {
  try {
    const { data: comments, error } = await supabase
      .from("comments")
      .select("*")
      .eq("post_id", postId)
      .order("created_at", { ascending: true });

    if (error) throw error;

    listContainer.innerHTML = "";

    if (!comments || comments.length === 0) {
      listContainer.innerHTML = `<div class="description" style="margin: 0; padding: 4px;">댓글이 없습니다.</div>`;
      return;
    }

    comments.forEach(comment => {
      const item = document.createElement("div");
      item.className = "comment-item";
      const dateString = new Date(comment.created_at).toLocaleString();
      item.innerHTML = `
        <div class="comment-meta">
          <span class="author">${escapeHtml(comment.commenter)}</span>
          <span>${dateString}</span>
        </div>
        <div class="comment-content">${escapeHtml(comment.content)}</div>
      `;
      listContainer.appendChild(item);
    });
  } catch (error) {
    listContainer.innerHTML = `<div class="description">댓글 로드 실패</div>`;
  }
}

// 댓글 등록
async function submitComment(postId, commenter, content, listContainer) {
  if (!commenter || !content) {
    return alert("작성자와 내용을 채워주세요.");
  }

  try {
    const { error } = await supabase
      .from("comments")
      .insert([{ post_id: postId, commenter, content }]);

    if (error) throw error;

    loadComments(postId, listContainer);
  } catch (error) {
    alert("댓글 작성 실패: " + error.message);
  }
}

// ==========================================
// 렌더링 헬퍼 함수
// ==========================================

async function createPostCardElement(post) {
  const card = document.createElement("div");
  card.className = "post-card";
  const dateString = new Date(post.created_at).toLocaleString();

  card.innerHTML = `
    <div class="post-card-header">
      <div>
        <h4 class="post-card-title">${escapeHtml(post.title)}</h4>
        <span class="post-card-meta">등록일: ${dateString}</span>
      </div>
    </div>
    <p class="post-card-body">${escapeHtml(post.content)}</p>
    <div class="post-card-actions">
      <button class="btn btn-outline btn-sm btn-edit">수정</button>
      <button class="btn btn-danger btn-sm btn-delete">삭제</button>
    </div>
    
    <div class="comments-container">
      <div class="comments-title">댓글 목록</div>
      <div class="comments-list" id="comments-list-${post.id}">로딩 중...</div>
      
      <form class="comment-form" id="comment-form-${post.id}">
        <input type="text" class="commenter-input" placeholder="작성자" required>
        <input type="text" class="content-input" placeholder="댓글 내용을 입력하세요" required>
        <button type="submit" class="btn btn-primary btn-sm">등록</button>
      </form>
    </div>
  `;

  const commentsList = card.querySelector(`#comments-list-${post.id}`);
  const commentForm = card.querySelector(`#comment-form-${post.id}`);

  loadComments(post.id, commentsList);

  commentForm.addEventListener("submit", (e) => {
    e.preventDefault();
    const commenter = commentForm.querySelector(".commenter-input").value.trim();
    const content = commentForm.querySelector(".content-input").value.trim();
    
    submitComment(post.id, commenter, content, commentsList);
    commentForm.querySelector(".content-input").value = "";
  });

  card.querySelector(".btn-edit").addEventListener("click", () => {
    updatePost(post.id, post.title, post.content);
  });
  
  card.querySelector(".btn-delete").addEventListener("click", () => {
    deletePost(post.id);
  });

  return card;
}

function escapeHtml(str) {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
