/**
 * -----------------------------------------------------------------------------------
 * [실습 2] Supabase Storage & Profile 아바타 연동 실습
 * -----------------------------------------------------------------------------------
 * [데이터베이스 및 버킷 준비 가이드]
 * 
 * -- 1. 프로필 테이블 생성
 * create table profiles (
 *   id bigint generated by default as identity primary key,
 *   nickname text not null,
 *   avatar_url text,
 *   updated_at timestamp with time zone default now() not null
 * );
 * 
 * -- 2. Storage 버킷 설정
 * --  - Supabase Dashboard -> Storage 메뉴로 이동
 * --  - "New Bucket"을 클릭해 'avatars' 이름으로 버킷 생성
 * --  - ⚠️ 중요: "Public bucket" 옵션을 활성화해 주세요.
 * --    (Public 옵션을 켜야 백엔드 서버를 거치지 않고 직접 이미지 URL로 이미지 렌더링이 가능해집니다.)
 * -----------------------------------------------------------------------------------
 */

// 1. Supabase 접속 설정값 (사용자 정보로 대체 필요)
const SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL"; 
const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"; 

let supabase = null;

// 애플리케이션 초기화
document.addEventListener("DOMContentLoaded", () => {
  initSupabase();
  fetchProfiles();
  bindEvents();
});

// Supabase 클라이언트 생성
function initSupabase() {
  if (SUPABASE_URL === "YOUR_SUPABASE_PROJECT_URL" || SUPABASE_ANON_KEY === "YOUR_SUPABASE_ANON_KEY") {
    console.warn("Supabase 접속을 위해 script.js 상단의 URL과 Key 값을 변경해 주세요.");
    return;
  }
  supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
}

// 이벤트 핸들러 바인딩
function bindEvents() {
  const profileForm = document.getElementById("profile-form");
  if (profileForm) {
    profileForm.addEventListener("submit", handleProfileSubmit);
  }

  const fileInput = document.getElementById("avatar-file");
  if (fileInput) {
    fileInput.addEventListener("change", handleFileSelection);
  }

  const refreshBtn = document.getElementById("btn-refresh");
  if (refreshBtn) {
    refreshBtn.addEventListener("click", fetchProfiles);
  }
}

// ==========================================
// 파일 선택 및 업로드 로직
// ==========================================

// 파일 선택 시 임시 로컬 URL로 화면의 아바타 이미지 미리보기 업데이트
function handleFileSelection(e) {
  const fileInput = e.target;
  const fileNameDisplay = document.getElementById("file-name-display");
  const avatarImg = document.getElementById("avatar-img");

  if (fileInput.files && fileInput.files.length > 0) {
    const file = fileInput.files[0];
    fileNameDisplay.textContent = file.name;
    avatarImg.src = URL.createObjectURL(file);
  } else {
    fileNameDisplay.textContent = "선택된 파일이 없습니다.";
  }
}

// [Storage Upload] 파일을 Supabase Storage에 업로드하고 Public URL을 반환
// [참고] 만약 Storage 버킷에 "로그인한 사용자만 파일 업로드 가능(RLS)" 정책을 설정한다면,
// 앞의 실습 1에서 구축한 이메일 가입/로그인(Auth) 기능을 통해 사용자 세션을 먼저 획득한 뒤 이 업로드 함수를 연동하도록 구현할 수도 있습니다.
async function uploadAvatarToStorage(file) {
  const fileExt = file.name.split('.').pop();
  const fileName = `${Date.now()}_avatar.${fileExt}`;
  const filePath = `public/${fileName}`;

  // avatars 버킷으로 파일 업로드 호출
  const { data, error } = await supabase.storage
    .from("avatars")
    .upload(filePath, file, {
      cacheControl: '3600',
      upsert: false
    });

  if (error) {
    throw error;
  }

  // 업로드 성공 후 버킷이 Public 상태일 때 바로 접근 가능한 Public URL 획득
  const { data: { publicUrl } } = supabase.storage
    .from("avatars")
    .getPublicUrl(filePath);

  return publicUrl;
}

// ==========================================
// 프로필 관리 DB 로직
// ==========================================

// 닉네임과 업로드된 이미지 주소를 profiles 테이블에 매핑하여 저장
async function handleProfileSubmit(e) {
  e.preventDefault();
  if (!supabase) return alert("Supabase 설정을 완료해 주세요.");

  const fileInput = document.getElementById("avatar-file");
  const nicknameInput = document.getElementById("profile-nickname");
  const loader = document.getElementById("avatar-loader");

  const nickname = nicknameInput.value.trim();
  const file = fileInput.files[0];

  if (!nickname) {
    return alert("닉네임을 입력해 주세요.");
  }

  loader.classList.remove("hidden");

  try {
    let finalAvatarUrl = null;

    // 1. 파일이 업로드된 경우 스토리지로 먼저 전송
    if (file) {
      finalAvatarUrl = await uploadAvatarToStorage(file);
    } else {
      finalAvatarUrl = document.getElementById("avatar-img").src;
    }

    // 2. 최종 획득한 스토리지 이미지 경로와 닉네임을 테이블에 저장
    const { error } = await supabase
      .from("profiles")
      .insert([{
        nickname: nickname,
        avatar_url: finalAvatarUrl
      }]);

    if (error) throw error;

    alert("프로필 정보가 성공적으로 저장되었습니다.");
    
    // 입력창 리셋
    fileInput.value = "";
    document.getElementById("file-name-display").textContent = "선택된 파일이 없습니다.";
    nicknameInput.value = "";

    fetchProfiles();
  } catch (error) {
    alert("저장 실패: " + error.message);
  } finally {
    loader.classList.add("hidden");
  }
}

// 등록된 전체 사용자 프로필 목록 조회 및 렌더링
async function fetchProfiles() {
  const grid = document.getElementById("profiles-grid");
  if (!supabase) {
    grid.innerHTML = `<div class="status-msg">접속 정보가 설정되지 않았습니다.</div>`;
    return;
  }

  grid.innerHTML = `<div class="status-msg">데이터 로딩 중...</div>`;

  try {
    const { data: profiles, error } = await supabase
      .from("profiles")
      .select("*")
      .order("updated_at", { ascending: false });

    if (error) throw error;

    if (!profiles || profiles.length === 0) {
      grid.innerHTML = `<div class="status-msg">등록된 프로필이 없습니다.</div>`;
      return;
    }

    grid.innerHTML = "";
    profiles.forEach(profile => {
      const card = document.createElement("div");
      card.className = "profile-card-item";

      const imgUrl = profile.avatar_url || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150";

      card.innerHTML = `
        <img class="profile-avatar-thumbnail" src="${imgUrl}" alt="${escapeHtml(profile.nickname)} 아바타">
        <div class="profile-nickname-text">${escapeHtml(profile.nickname)}</div>
      `;

      grid.appendChild(card);
    });
  } catch (error) {
    grid.innerHTML = `<div class="status-msg">목록 조회 실패: ${error.message}</div>`;
  }
}

// XSS 방지용 HTML 이스케이프 헬퍼 함수
function escapeHtml(str) {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
